# Generated by Django 5.2.8 on 2025-11-21 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('content', models.JSONField()),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard')])),
                ('pronunciation_guide', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('character', models.CharField(default='👤', max_length=10)),
                ('stars', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('voice_gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl')], default='boy', max_length=10)),
                ('voice_pitch', models.FloatField(default=1.0)),
                ('voice_rate', models.FloatField(default=1.0)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_playtime_minutes', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username'], name='main_userpr_usernam_601fa7_idx'), models.Index(fields=['created_at'], name='main_userpr_created_bb7464_idx')],
            },
        ),
        migrations.CreateModel(
            name='PronunciationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('times_heard', models.IntegerField(default=0)),
                ('times_practiced', models.IntegerField(default=0)),
                ('proficiency_level', models.IntegerField(choices=[(0, 'New'), (1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'Mastered')], default=0)),
                ('last_practiced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_logs', to='main.userprogress')),
            ],
            options={
                'ordering': ['-last_practiced'],
                'unique_together': {('user', 'item')},
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_id', models.CharField(max_length=50)),
                ('chapter_name', models.CharField(default='', max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('attempts', models.IntegerField(default=0)),
                ('best_attempt', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='main.userprogress')),
            ],
            options={
                'ordering': ['chapter_id'],
                'indexes': [models.Index(fields=['user', 'chapter_id'], name='main_chapte_user_id_5e41bc_idx'), models.Index(fields=['is_completed'], name='main_chapte_is_comp_b19ff4_idx')],
                'unique_together': {('user', 'chapter_id')},
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('badge_icon', models.CharField(max_length=10)),
                ('achievement_type', models.CharField(choices=[('stars', 'Star Collector'), ('speed', 'Speed Learner'), ('accuracy', 'Perfect Score'), ('streak', 'Learning Streak'), ('milestone', 'Major Milestone')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='main.userprogress')),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge_name')},
            },
        ),
    ]
